camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
model:
   graph: 'perception/frozen_inference_graph-real.pb'
   labels: 'perception/label_map-real.pbtxt'
